-- what is total revenue generated by male and female customers?
select gender , sum(purchase_amount) as revenue
from customer
group by gender

-- which customers used a discount but still spent more than the average purchase amouont?

select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)
-- which are the top 5 products with the highhest average review rating

select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average product rating" 
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

